### ISSUE TITLE
Need guidance to use PureMVC in Xamarin.forms

### ISSUE THREAD

**Issue by vivek-chowdhury** [PureMVC/puremvc-csharp-standard-framework#4]
Hi,
I am new in Xamarin and want to use PureMVC in xamarin cross platform project. So, I request you to please guide me from where i can get sample example of PureMVC for Xamarin? 
I need this because as per Xamarin.form every xaml files has its helper class and that helper class is extended by ContentPage or ContentView. So, my question is how can we extend Mediator of PureMVC in any Page or Component.

Thank & Regards
Vivek

**Comment by saadshams** [comment]
Hi Vivek,

Every xaml file and it's associated helper class is treated as a viewComponent, therefore it will be managed by the Mediator of PureMVC rather than extending Mediator by any other entity.

You've to pass the reference of the main application to the Facade and then StartupCommand and from there a Mediator can receive a reference to your application or sub-components of the application while registering itself with Facade.

If you have an isolated version of a sample application on GitHub I can help you further out. Hope above helps.
